[phases.setup]
nixPkgs = ['nodejs_20', 'vips']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = [
  'npm run build',
  'mkdir -p dist/server/db && cp -r src/db/migrations dist/server/db/migrations',
]

[start]
cmd = 'node ./dist/server/entry.mjs'

[variables]
NODE_ENV = 'production'
